---
functional:
  - Пользователь должен иметь возможность зарегистрироваться, войти в свой профиль, выйти из профиля, удалить профиль
  - Создание игры доступно только авторизованным пользователям
  - Язык программирования выбирается в процессе игры и не должен быть привязан к созданию сессии
  - После создании игры с другим игроком - переход в режим ожидания второго игрока, игра отображается в списке "доступных для подключения"
  - При подключении к игре оба игрока переносятся в игровое пространство
  - В игровом пространстве присутствуют два редактора (слева - свой, справа - соперника)
  - Задание располагается сверху, время игры под ним, чат слева
  - Когда соперник набирает код, это должно быть видно в реальном времени
  - Возможность запустить проверку кода — неограниченное количество раз
  - Тесты запускаются только на локальном коде, не на коде соперника
  - При успешной проверке должно появиться модальное окно - победитель определён
  - При победе кнопка "Check" блокируется. Появляется кнопка "Exit". Победитель может остаться и смотреть на код
  - Проигравший может продолжать писать и проверять (но победитель уже найден). Может выйти. Игра удаляется из памяти только после выхода обоих
  - Игра может длиться неограниченно. Нет таймера на победу - игра идет до первого успешного решения

non-functional:
  - Сайт должен являться SPA-приложением, не перезагружать страницы (GitHub wiki - технологии - React)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен иметь адаптивный дизайн
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Должна быть осуществлена поддержка переподключения при разрыве соединения

implicit:
  - Логотип должен вести на главную страницу
  - Должна быть возможность отключить режим ожидания второго игрока
  - Пробная игра без регистрации
  - На главной странице размещен виджет с краткой информацией о текущем пользователе (никнейм, принадлежность к клану, elo_rating, place, points), текущий сезон, ссылка на "Зал славы", и кнопками "Create a battle" и "Join a battle"
  - На главной расположен чат со списком сообщений, которые можно фильтровать (General, Нотификация, Приватные сообщения)
  - Пользователю online можно написать приватное сообщение, перейти на страницу его профиля, подписаться на него и отписаться, приостановить подписку, вызвать на бой, отменить вызов на бой (у обоих игроков)
  - При нажатии "подписаться", происходит редирект на бои участника. Перед редиректом выводится предупреждение, что сейчас произойдет редирект, который можно отменить
  - В области чата и в шапке сайта отображается количество игроков online
  - В профиле пользователя должны отображаться статистика (rank, elo_rating, games played, points, календарь активности, ссылка на сервис Holopin), список завершенных игр
  - Список завершенных игр отображается в виде таблицы (Level, Players, Date, Actions), рядом с никнеймом игрока отображается количество очков, полученных в текущем бою (1 при победе и -1 при поражении), можно перейти на страницу информации о пользователе
  - При наведении курсора на никнейм появляется tooltip, где отображается информация о пользователе (никнейм, язык программирования, rank, elo_rating, games played, количество побед, проигрышей, сколько раз игрок сдался)
  - В списке завершенных игр имеется возможность зайти в игру
  - На странице настроек профиля должна быть возможность изменить никнейм, язык программирования, локализацию, выбрать тип звукового сопровождения, громкость, а также сохранить настройки
  - Настройки должны сохраняться между сессиями
  - Возможность создать клан или вступить в уже существующий, просмотреть список существующих кланов, список можно сортировать, фильтровать по создателю, осуществлять поиск, вывод списка с использованием пагинации
  - На сайте должна быть страница "Зал славы", на которой отображается статистика по текущему сезону; карточки Top 3 игрока; Top 3 чемпиона предыдущего сезона; таблица лидеров. В таблице есть просмотр статистики каждого участника. Таблицу можно отфильтровать по никнейму, клану, языку программирования, сортировать по столбцам
  - На сайте должна быть страница "Расписание турниров", на ней отображается календарь с историей всех соревнований, а также история соревнований, созданных пользователем, с возможностью просмотреть события за месяц (month), список событий по часам конкретного дня (day), расписание на все дни месяца (agenda), в календаре навигация по месяцу, дню, с возможностью просмотреть подробное расписание на месяц
  - Страница "Tournaments" содержит список созданных турниров в виде таблицы, с возможностью просмотреть результаты каждого турнира и форму для ввода параметров турнира для создания турниров
  - Если турнир не завершен есть возможность присоединиться к нему (отображение в списке участников), выйти из турнира (удаление из списка)
