---
functional:
  - Должна быть возможность попробовать сыграть без регистрации
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность войти в свой профиль
  - Пользователь должен иметь возможность выйти из своего профиля
  - Создание игры доступено только авторизованным пользователям
  - Создание игры по кнопке "Create game"
  - Язык программирования выбирается в процессе игры и не должен быть привязан к созданию сессии
  - После создании игры с другим игроком - переход в режим ожидания второго игрока
  - После создании игры с другим игроком - игра отображается в списке "доступных для подключения"
  - Второй игрок подключается по нажатию "Connect to game"
  - При подключении к игре оба игрока переносятся в игровое пространство



non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя  
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен иметь адаптивный дизайн
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен иметь локализацию (перевод) на русский и английский языки


implicit:
  - Логотип должен вести на главную страницу
  - В меню выбора языка интерфейса должны отображаться наименование языка и индикатор языка в виде флага
  - Должна быть возможность отключить режим ожидания второго игрока
