---
functional:
  - Пользователь должен иметь возможность зарегистрироваться, войти в свой профиль, выйти из профиля, удалить профиль
  - Создание игры доступно только авторизованным пользователям
  - Язык программирования выбирается в процессе игры и не должен быть привязан к созданию сессии
  - После создании игры с другим игроком - переход в режим ожидания второго игрока, игра отображается в списке "доступных для подключения"
  - При подключении к игре оба игрока переносятся в игровое пространство
  - Когда соперник набирает код, это должно быть видно в реальном времени
  - Возможность запустить проверку кода — неограниченное количество раз
  - Тесты запускаются только на локальном коде, не на коде соперника
  - При успешной проверке должно появиться модальное окно - победитель определён
  - При победе кнопка "Check" блокируется. Появляется кнопка "Exit". Победитель может остаться и смотреть на код
  - Проигравший может продолжать писать и проверять (но победитель уже найден). Может выйти. Игра удаляется из памяти только после выхода обоих

non-functional:
  - Сайт должен являться SPA-приложением, не перезагружать страницы (GitHub wiki - технологии - React)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен иметь адаптивный дизайн
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - В игровом пространстве присутствуют два редактора (слева - свой, справа - соперника)
  - Задание распологается сверху, время игры под ним, чат слева
  - Должна быть осуществлена поддержка переподключения при разрыве соединения
  - Игра может длиться неограниченно. Нет таймера на победу - игра идет до первого успешного решения

implicit:
  - Логотип должен вести на главную страницу
  - Должна быть возможность выбора языка интерфейса
  - Должна быть возможность отключить режим ожидания второго игрока
  - Пробная игра без регистрации
  - На главной странице размещен виджет с краткой информацией о текущем пользователе (никнейм, принадлежность к клану, elo_rating, place, points), текущий сезон, ссылкой на "Зал славы", и кнопками "Create a battle" и "Join a battle"
  - На главной расположен чат со списком сообщений, которые можно фильтровать
  - Пользователю online можно написать приватное сообщение, перейти на страницу его профиля, скопировать его никнейм, подписаться на него и отписаться, вызвать на бой
  - При нажатии "подписаться", происходит редирект на бои участника. Перед редиректом выводится предупреждение, что сейчас произойдет редирект, который можно отменить
  - При приглашении на бой появляется всплывающее окно с никнеймом игрока, которого пригласил и кнопка "Cancel". У приглашенного игрока всплывающее окно с именем пригласившего и кнопки "Accept" и "Decline"
  - В области чата и в шапке сайта отображается количество игроков online
  - С главной можно перейти на страницы "Contests history", "My tournaments", "Create a tournament"
  - Пользователь может создать турнир, после этого он должен отобразиться на странице "Мои турниры"
  - В профиле пользователя должна отображаться статистика (rank, elo_rating, games played, points, список завершенных игр), аватар, никнейм, выбранный язык программирования, дата регистрации на сайте, достижения, календарь активности, ссылка на сервис Holopin
  - Список завершенных игр отображается в виде таблицы (Level, Players, Date, Actions)
  - Рядом с никнеймом игрогка отображается количество очков, полученных в текущем бою. 1 - при победе и -1 при поражении
  - При наведении курсора на никнейм появляется tooltip, где отображаются информация о пользователе (никнейм, язык программирования, rank, elo_rating, games played, количество побед, проигрышей, сколько раз игрок сдался)
  - В списке завершенных игр имеется возможность простомтреть завершенную игру
  - На странице настроек профиля должна быть возможность изменить никнейм, язык программирования, локализацию, выбрать тип звукового сопровождения, громкость, а также сохранить настройки
  - Возможность прослушать, выбранное звуковое сопровождение
  - Настройки должны сохраняться между сессиями
  - Возможность создать клан или вступить в уже существующий
  - Просмотреть список существующих кланов
  - Должна быть возможность сортировки, фильтрации и поиск по списку кланов
  - Список кланов выводится с использованием пагинации
  - В списке кланов есть кнопка "Вступить в клан"
  - На сайте должна быть страница "Зал славы", на которой отображается статистика по текущему сезону; карточки Top 3 игрока (аватар, никнейм, язык программирования, points, wins, score, tournaments); таблица лидеров; Top 3 чампиона предыдущего сезона
  - Есть возможность просмотреть статистику по всем сезонам
  - В таблице есть просмотр статистики каждого участника
  - Таблицу можно отфильтровать по никнейму, клану, языку программированю
  - Таблицу можно сортировать по столбцам
  - На сайте должна быть страница "Расписание турнаментов", на ней отображается календарь с историей всех соревнований, а также история соревнований, созданных пользователем, с возможностью просмотреть события за месяц (month), список событий по часам (day), расписание дня (agenda)
  - В календаре навигация по месяцу
  - Страница "Create a tournament" содержит список созданных турниров в виде таблицы, с возможностью просмотреть результаты каждого турнира и форму для ввода параметров турнира
  - Если турнир не завершен есть возможность присоединиться к нему (отображение в списке участников), выйти из турнира (удаление из списка)
  - Форма создания турнира состоит из Basic Information, Schedule & Access, Tournament Features, Tournament Settings