---
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность войти в свой профиль
  - Пользователь должен иметь возможность выйти из своего профиля
  - Создание игры доступно только авторизованным пользователям
  - Язык программирования выбирается в процессе игры и не должен быть привязан к созданию сессии
  - После создании игры с другим игроком - переход в режим ожидания второго игрока
  - После создании игры с другим игроком - игра отображается в списке "доступных для подключения"
  - При подключении к игре оба игрока переносятся в игровое пространство
  - Когда соперник набирает код, это должно быть видно в реальном времени
  - Возможность запустить проверку кода — неограниченное количество раз
  - Тесты запускаются только на локальном коде, не на коде соперника
  - При успешной проверке должно появиться модальное окно - победитель определён
  - При победе кнопка “Check” блокируется. Появляется кнопка “Exit”. Победитель может остаться и смотреть на код
  - Проигравший может продолжать писать и проверять (но победитель уже найден). Может выйти. Игра удаляется из памяти только после выхода обоих


non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен иметь адаптивный дизайн
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - В игровом пространстве присутствуют два редактора (слева - свой, справа - соперника)
  - Задание распологается сверху, время игры под ним, чат слева
  - Должна быть осуществлена поддержка переподключения при разрыве соединения
  - Поддержка восстановления сессии по ID
  - Игра может длиться неограниченно. Нет таймера на победу - игра идет до первого успешного решения

  

implicit:
  - Логотип должен вести на главную страницу
  - В меню выбора языка интерфейса должны отображаться наименование языка и индикатор языка в виде флага
  - Должна быть возможность отключить режим ожидания второго игрока
  - Должна быть возможность попробовать сыграть без регистрации
